/* MINTFORGE UI layer. Keeps marketplace, checkout, Solana and Supabase logic in index.html. */
(function(){
const css=`
:root{--mf-line:rgba(255,255,255,.1);--mf-muted:#949ba7;--mf-mint:#9dff00}
html{scroll-behavior:smooth}body{background:radial-gradient(circle at 72% 20%,rgba(157,255,0,.07),transparent 30%),linear-gradient(180deg,#080a0c 0%,#050607 100%);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body:before{content:"";position:fixed;inset:0;pointer-events:none;z-index:-1;opacity:.045;background-image:linear-gradient(rgba(157,255,0,.35) 1px,transparent 1px),linear-gradient(90deg,rgba(157,255,0,.35) 1px,transparent 1px);background-size:52px 52px;mask-image:linear-gradient(90deg,transparent,#000 58%,transparent)}
header{height:76px;padding:0 max(4%,calc((100vw - 1280px)/2));background:rgba(7,9,11,.9);border-bottom:1px solid var(--mf-line);box-shadow:0 12px 35px rgba(0,0,0,.22);z-index:40}.logo{display:flex;align-items:center;font-size:21px;letter-spacing:.12em;font-weight:950}.logo:before{content:"MF";display:grid;place-items:center;width:32px;height:32px;margin-right:10px;border:1px solid var(--mf-mint);border-radius:10px;color:var(--mf-mint);font-size:10px;letter-spacing:-.05em;box-shadow:0 0 18px rgba(157,255,0,.12)}.logo span{color:var(--mf-mint)}.header-actions{gap:10px}.connect{background:var(--mf-mint);color:#071000;box-shadow:0 7px 25px rgba(157,255,0,.15)}.secondary{background:#11151a;border:1px solid var(--mf-line);color:#fff}
.mf-nav{display:flex;align-items:center;gap:3px;margin-left:auto;margin-right:12px}.mf-nav button{background:transparent;color:#c6cad0;padding:9px 11px;font-size:12px;font-weight:850}.mf-nav button:first-child{color:var(--mf-mint)}.mf-cart-btn{position:relative}.mf-cart-count{display:none;position:absolute;top:-1px;right:-1px;min-width:17px;height:17px;border-radius:50%;background:var(--mf-mint);color:#071000;font-size:9px;line-height:17px;font-weight:950;text-align:center}
.wrap{max-width:1280px;padding:64px max(4%,24px) 130px}.hero-brand{max-width:760px;margin:0 0 62px;text-align:left}.hero-brand .eyebrow{margin-bottom:18px}.hero-brand h1{font-size:clamp(54px,8vw,94px);line-height:.87;letter-spacing:-.065em;font-weight:950;margin:0 0 26px}.hero-brand h1 span{color:var(--mf-mint)}.hero-brand p{max-width:610px;margin:0;color:#aab0ba;font-size:16px;line-height:1.65}.hero-actions{justify-content:flex-start;margin-top:28px}.hero-actions button{min-width:190px}.mf-trust{justify-content:flex-start;margin:28px 0 0;max-width:600px}.mf-trust span{padding:8px 12px;border:1px solid var(--mf-line);border-radius:999px;background:rgba(255,255,255,.025);color:#aeb4bd;font-size:10px;font-weight:850;letter-spacing:.08em}.mf-trust span:first-child{color:var(--mf-mint);border-color:rgba(157,255,0,.25)}
.shop-heading{display:flex;align-items:end;justify-content:space-between;margin-bottom:22px}.shop-heading h2{font-size:34px;letter-spacing:-.04em;margin:7px 0 0}.shop-heading p{color:var(--mf-muted);font-size:13px;margin:0}.grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.card{background:linear-gradient(145deg,#11151a,#0b0e11);border:1px solid var(--mf-line);border-radius:20px;box-shadow:0 15px 45px rgba(0,0,0,.2);transition:transform .2s,border-color .2s}.card:hover{transform:translateY(-4px);border-color:rgba(157,255,0,.28)}.art{height:245px;background:radial-gradient(circle at 50% 40%,rgba(157,255,0,.14),transparent 52%),#0a0d10}.body{padding:18px}.body h3{font-size:18px}.buy{background:#fff;color:#08090c}.buy:hover{background:var(--mf-mint)}
.cart{z-index:60;background:rgba(12,15,18,.97);border-color:rgba(157,255,0,.18);box-shadow:0 30px 100px rgba(0,0,0,.7);backdrop-filter:blur(20px)}.modal{backdrop-filter:blur(10px)}.modal-card{background:linear-gradient(145deg,#11151a,#090b0e);border-color:var(--mf-line)}.field input,.field select,.field textarea{background:#080b0e;border-color:var(--mf-line)}.field input:focus,.field select:focus,.field textarea:focus{border-color:rgba(157,255,0,.55);box-shadow:0 0 0 3px rgba(157,255,0,.08)}
.mf-bottom-nav{display:none}.mf-image-upload{border:1px dashed rgba(157,255,0,.38);border-radius:16px;padding:18px;background:linear-gradient(145deg,rgba(157,255,0,.055),rgba(255,255,255,.018));text-align:center;cursor:pointer}.mf-image-upload input{display:none!important}.mf-image-upload .mf-upload-icon{font-size:28px;margin-bottom:6px}.mf-image-upload strong{display:block;font-size:14px}.mf-image-upload span{display:block;color:var(--mf-muted);font-size:11px;margin-top:5px}.mf-image-preview{display:none;margin-top:12px;border-radius:13px;overflow:hidden;border:1px solid var(--mf-line);background:#080b0e}.mf-image-preview img{display:block;width:100%;max-height:240px;object-fit:contain}.mf-image-name{padding:8px 10px;color:#aeb4bd;font-size:11px}.mf-upload-status{font-size:11px;margin-top:8px;color:var(--mf-muted)}
.mf-product-detail .modal-card{width:min(760px,100%);padding:0;overflow:hidden}.mf-detail-image{width:100%;max-height:420px;object-fit:cover;background:#090c10;display:block}.mf-detail-body{padding:24px}.mf-detail-price{color:var(--mf-mint);font-size:25px;font-weight:950;margin:12px 0}.mf-detail-meta{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0}.mf-detail-meta span{border:1px solid var(--mf-line);border-radius:999px;padding:7px 10px;color:#aeb4bd;font-size:10px;font-weight:800}.mf-detail-actions{display:flex;gap:10px;margin-top:20px}.mf-detail-actions button{flex:1}.mf-card-clickable{cursor:pointer}
@media(max-width:900px){.mf-nav{display:flex}.wrap{padding-left:4%;padding-right:4%}.grid{grid-template-columns:repeat(3,minmax(210px,1fr));overflow-x:auto;scroll-snap-type:x mandatory;padding-bottom:8px}.grid .card{scroll-snap-align:start}.art{height:210px}}
@media(max-width:620px){body{padding-bottom:72px}header{height:70px;padding:0 4%}.logo{font-size:18px}.logo:before{width:31px;height:31px}.wallet-mini{display:none}.header-actions{gap:5px}.connect{padding:10px 13px;font-size:10px}.mf-nav{gap:0;margin-right:4px}.mf-nav button{padding:8px 6px;font-size:10px}.mf-nav button[data-mf-sell]{display:none}.mf-cart-btn{font-size:0!important;width:32px}.mf-cart-btn:after{content:"🛒";font-size:19px}.mf-cart-count{font-size:9px}.wrap{padding:48px 4% 110px}.hero-brand{margin:0 0 56px;max-width:none}.hero-brand h1{font-size:clamp(48px,15vw,68px);line-height:.88}.hero-brand p{font-size:14px}.hero-actions{display:flex;gap:10px}.hero-actions button{min-width:0;flex:1;padding:13px 10px;font-size:11px}.mf-trust{display:grid;grid-template-columns:1fr 1fr;gap:8px}.mf-trust span{font-size:9px;text-align:center;padding:9px 6px}.shop-heading{align-items:end;margin-bottom:18px}.shop-heading h2{font-size:30px}.shop-heading p{font-size:12px}.grid{display:flex;gap:12px;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;margin-right:-4vw;padding-right:4vw}.grid::-webkit-scrollbar{display:none}.grid .card{flex:0 0 185px;min-width:185px;scroll-snap-align:start;border-radius:18px}.grid .art{height:180px}.grid .body{padding:12px}.grid .body h3{font-size:15px;line-height:1.2}.grid .body p{display:none}.grid .row{display:block}.grid .buy{display:block;width:100%;margin-top:9px;padding:9px 7px;font-size:10px}.grid .stock{font-size:9px;margin-top:7px}.grid .body b{display:block;color:var(--mf-mint);font-size:15px;margin-top:8px}.mf-bottom-nav{position:fixed;display:grid;grid-template-columns:repeat(4,1fr);left:0;right:0;bottom:0;height:68px;z-index:55;background:rgba(12,15,19,.97);border-top:1px solid var(--mf-line);backdrop-filter:blur(18px)}.mf-bottom-nav button{background:transparent;color:#858b95;border-radius:0;padding:7px 2px 5px;font-size:10px;font-weight:750;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px}.mf-bottom-nav button span{font-size:21px;line-height:20px}.mf-bottom-nav button.active{color:var(--mf-mint)}.cart{right:8px;bottom:78px;width:calc(100% - 16px);max-height:80vh}.modal{padding:8px}.modal-card{padding:20px;border-radius:20px}.mf-product-detail .modal-card{padding:0}.mf-detail-image{max-height:330px}.mf-detail-body{padding:18px}.mf-detail-actions{flex-direction:column}}
`;
const style=document.createElement('style');style.id='mintforge-brand-layer';style.textContent=css;document.head.appendChild(style);
function fillCountries(){const selects=document.querySelectorAll('#shipCountry,#profileCountry');if(!selects.length)return;let codes=[];try{codes=Intl.supportedValuesOf('region').filter(x=>/^[A-Z]{2}$/.test(x))}catch(e){codes=['AU','NZ','US','CA','GB','DE','FR','ES','IT','JP','SG','ID','IN']}const names=new Intl.DisplayNames(['en'],{type:'region'});selects.forEach(sel=>{if(sel.options.length>1)return;codes.sort((a,b)=>names.of(a).localeCompare(names.of(b))).forEach(code=>{const o=document.createElement('option');o.value=code;o.textContent=names.of(code);sel.appendChild(o)});if(!sel.value)sel.value='AU'})}
function addHeaderNav(){const header=document.querySelector('header'),actions=header?.querySelector('.header-actions');if(!header||!actions||document.querySelector('.mf-nav'))return;const nav=document.createElement('nav');nav.className='mf-nav';nav.innerHTML='<button data-mf-shop>EXPLORE⌄</button><button data-mf-sell>SELL</button><button data-mf-cart class="mf-cart-btn">CART <span class="mf-cart-count">0</span></button>';header.insertBefore(nav,actions)}
function addHero(){const main=document.querySelector('main.wrap');if(!main||document.querySelector('.hero-brand'))return;const old=[main.querySelector(':scope>.eyebrow'),main.querySelector(':scope>h1'),main.querySelector('#walletLabel')];const hero=document.createElement('section');hero.className='hero-brand';hero.innerHTML='<div class="eyebrow">SOLANA NATIVE MARKETPLACE</div><h1>FORGE IT.<br><span>MINT IT.</span><br>OWN IT.</h1><p>Premium physical goods from independent creators, with fast, native Solana checkout built in.</p><div class="hero-actions"><button class="primary" data-mf-shop>EXPLORE PRODUCTS&nbsp; →</button><button class="secondary" data-mf-sell>START SELLING</button></div><div class="mf-trust"><span>✓ SOLANA PAYMENTS</span><span>▣ PHYSICAL GOODS</span><span>▤ SELLER STOREFRONTS</span><span>▱ TRACKED SHIPPING</span></div></section>';main.insertBefore(hero,main.firstChild);old.forEach(x=>{if(x)x.style.display='none'});const title=main.querySelector('#products')?.previousElementSibling;if(title&&title.tagName==='H2'){const head=document.createElement('div');head.className='shop-heading';head.innerHTML='<div><div class="eyebrow">SHOP THE MARKETPLACE</div><h2>Featured products</h2></div><p>Made by creators. Bought with SOL.</p>';title.replaceWith(head)}}
function addBottomNav(){if(document.querySelector('.mf-bottom-nav'))return;const nav=document.createElement('nav');nav.className='mf-bottom-nav';nav.innerHTML='<button class="active" data-mf-shop><span>⌂</span>Explore</button><button data-mf-categories><span>▦</span>Categories</button><button data-mf-sell><span>⊕</span>Sell</button><button data-mf-account><span>♙</span>Account</button>';document.body.appendChild(nav);nav.querySelector('[data-mf-categories]').onclick=()=>document.querySelector('#products')?.scrollIntoView({behavior:'smooth'});nav.querySelector('[data-mf-account]').onclick=()=>{if(typeof openAccount==='function')openAccount('orders')}}
function updateBadge(){const n=typeof cart!=='undefined'?cart.reduce((a,x)=>a+Number(x.quantity||0),0):0;document.querySelectorAll('.mf-cart-count').forEach(x=>{x.textContent=n;x.style.display=n?'block':'none'})}
function bindNavigation(){document.querySelectorAll('[data-mf-shop]').forEach(b=>b.onclick=()=>document.querySelector('#products')?.scrollIntoView({behavior:'smooth',block:'start'}));document.querySelectorAll('[data-mf-sell]').forEach(b=>b.onclick=()=>{if(typeof openAccount==='function')openAccount('store');else if(typeof connect==='function')connect()});document.querySelectorAll('[data-mf-account]').forEach(b=>b.onclick=()=>{if(typeof openAccount==='function')openAccount('orders')});document.querySelectorAll('[data-mf-cart]').forEach(b=>b.onclick=()=>document.getElementById('cart')?.classList.add('open'));updateBadge()}
function initBrand(){fillCountries();addHeaderNav();addHero();addBottomNav();bindNavigation()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initBrand);else initBrand();

/* Product detail + add-to-cart repair. Mobile CSS previously hid the existing ADD TO CART button. */
(function(){
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]))}
function shippingLabel(p){const s=String(p?.shipping_strategy||p?.shipping_mode||'free');return s==='free'?'Free shipping':s==='worldwide_flat'?'Worldwide flat rate':'Flat-rate shipping'}
function detailModal(){let m=document.getElementById('mfProductDetail');if(m)return m;m=document.createElement('div');m.id='mfProductDetail';m.className='modal mf-product-detail';m.innerHTML='<div class="modal-card"><button class="close-x" id="mfDetailClose" style="position:absolute;right:18px;top:18px;z-index:2">×</button><img id="mfDetailImage" class="mf-detail-image" alt=""><div class="mf-detail-body"><div class="eyebrow" id="mfDetailCategory"></div><h2 id="mfDetailName"></h2><div class="mf-detail-price" id="mfDetailPrice"></div><p class="muted" id="mfDetailDescription"></p><div class="mf-detail-meta"><span id="mfDetailStock"></span><span id="mfDetailShipping"></span></div><div class="mf-detail-actions"><button class="secondary" id="mfDetailClose2">CLOSE</button><button class="primary" id="mfDetailAdd">ADD TO CART</button></div><div class="status" id="mfDetailStatus"></div></div></div>';document.body.appendChild(m);const close=()=>m.classList.remove('open');m.querySelector('#mfDetailClose').onclick=close;m.querySelector('#mfDetailClose2').onclick=close;m.addEventListener('click',e=>{if(e.target===m)close()});return m}
function openDetail(p){if(!p)return;const m=detailModal();const image=m.querySelector('#mfDetailImage');image.src=p.image_url||'';image.style.display=p.image_url?'block':'none';image.alt=p.name||'Product';m.querySelector('#mfDetailCategory').textContent=p.category||'3D PRINT';m.querySelector('#mfDetailName').textContent=p.name||'Product';m.querySelector('#mfDetailPrice').textContent=`$${Number(p.price||0).toFixed(2)} AUD`;m.querySelector('#mfDetailDescription').textContent=p.description||'Premium physical product from a MINTFORGE creator.';m.querySelector('#mfDetailStock').textContent=`${Number(p.stock||0)} in stock`;m.querySelector('#mfDetailShipping').textContent=shippingLabel(p);const add=m.querySelector('#mfDetailAdd');add.disabled=Number(p.stock)<1;add.textContent=Number(p.stock)<1?'SOLD OUT':'ADD TO CART';add.onclick=()=>{if(typeof addToCart==='function'){addToCart(p.id);m.classList.remove('open')}else{m.querySelector('#mfDetailStatus').textContent='Cart is temporarily unavailable.'}};m.classList.add('open')}
function enhanceCards(){const root=document.getElementById('products');if(!root)return;root.querySelectorAll('.card').forEach(card=>{if(card.dataset.mfEnhanced)return;const add=card.querySelector('[data-add]');if(!add)return;card.dataset.mfEnhanced='1';card.classList.add('mf-card-clickable');const id=add.dataset.add;card.addEventListener('click',e=>{if(e.target.closest('button'))return;const p=(typeof products!=='undefined'&&products.find(x=>String(x.id)===String(id)));if(p)openDetail(p)});add.style.display='block';add.textContent=Number((typeof products!=='undefined'&&products.find(x=>String(x.id)===String(id))?.stock)||0)<1?'SOLD OUT':'ADD TO CART';add.onclick=e=>{e.stopPropagation();if(typeof addToCart==='function')addToCart(id)}})}
function patchRender(){if(typeof renderProducts==='function'&&!window.__mfRenderProductsPatched){const original=renderProducts;window.__mfRenderProductsPatched=true;window.renderProducts=function(){original();enhanceCards();updateBadge()}}enhanceCards()}
function init(){patchRender();const root=document.getElementById('products');if(root)new MutationObserver(enhanceCards).observe(root,{childList:true});setInterval(patchRender,1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else setTimeout(init,0);
})();

/* Seller image upload from phone. */
(function(){
const UPLOAD_FN='https://zezusfnbqvijldhxoejd.supabase.co/functions/v1/seller-image-upload',API_KEY='sb_publishable_ax8du05SKISdpJQkXb3Ulw_0YJKQTjz';
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]))}
function currentSession(){const wallet=(document.getElementById('listingWallet')?.textContent||'').trim();return wallet?localStorage.getItem('mf_session_'+wallet):null}
function setupImageUpload(){const input=document.getElementById('listingImage');if(!input||document.getElementById('mfImageFile'))return;const field=input.closest('.field');if(!field)return;input.style.display='none';input.setAttribute('aria-hidden','true');const label=field.querySelector('label');if(label)label.textContent='PRODUCT IMAGE';const box=document.createElement('label');box.className='mf-image-upload';box.htmlFor='mfImageFile';box.innerHTML='<div class="mf-upload-icon">📷</div><strong>Upload image from your phone</strong><span>Tap to choose a product photo • JPG, PNG, WEBP or GIF</span><input id="mfImageFile" type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/*">';field.appendChild(box);const preview=document.createElement('div');preview.className='mf-image-preview';preview.id='mfImagePreview';field.appendChild(preview);const status=document.createElement('div');status.className='mf-upload-status';status.id='mfImageStatus';field.appendChild(status);const file=box.querySelector('input');file.addEventListener('change',()=>previewFile(file.files?.[0]));showExistingPreview(input.value)}
function showExistingPreview(url){const p=document.getElementById('mfImagePreview');if(!p||!url)return;p.style.display='block';p.innerHTML=`<img src="${esc(url)}" alt="Current product image"><div class="mf-image-name">Current product image • choose a new photo to replace it</div>`}
function previewFile(file){const p=document.getElementById('mfImagePreview'),s=document.getElementById('mfImageStatus');if(!p||!s||!file)return;if(!file.type.startsWith('image/')){s.textContent='Please choose an image file.';return}const r=new FileReader();r.onload=()=>{p.style.display='block';p.innerHTML=`<img src="${esc(r.result)}" alt="Selected product image"><div class="mf-image-name">${esc(file.name)}</div>`;s.textContent='Ready to upload when you save the listing.'};r.readAsDataURL(file)}
function dataUrlParts(data){const m=String(data).match(/^data:([^;]+);base64,(.+)$/);if(!m)throw Error('Could not prepare the image.');return{mime:m[1],base64:m[2]}}
async function compressImage(file){if(file.type==='image/gif')return file;const bitmap=await createImageBitmap(file);const max=1800,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),w=Math.max(1,Math.round(bitmap.width*scale)),h=Math.max(1,Math.round(bitmap.height*scale));const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0,w,h);bitmap.close?.();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.88));if(!blob)throw Error('Could not prepare the image.');return new File([blob],(file.name.replace(/\.[^.]+$/,'')||'product')+'.webp',{type:'image/webp'})}
async function uploadSelectedImage(){const file=document.getElementById('mfImageFile')?.files?.[0];if(!file)return document.getElementById('listingImage')?.value?.trim()||'';const token=currentSession();if(!token)throw Error('Please connect your wallet before uploading an image.');const s=document.getElementById('mfImageStatus');if(s)s.textContent='Preparing image…';const prepared=await compressImage(file);const reader=new FileReader();const data=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Could not read image.'));reader.readAsDataURL(prepared)});const parts=dataUrlParts(data);if(s)s.textContent='Uploading image…';const r=await fetch(UPLOAD_FN,{method:'POST',headers:{'Content-Type':'application/json','apikey':API_KEY},body:JSON.stringify({session_token:token,mime_type:parts.mime,data_base64:parts.base64})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.url)throw Error(d.error||'Image upload failed.');if(s)s.innerHTML='<span class="success">Image uploaded ✓</span>';return d.url}
function bindListingUpload(){setupImageUpload();const btn=document.getElementById('saveListing');if(!btn||btn.dataset.mfUploadBound)return;btn.dataset.mfUploadBound='1';btn.onclick=async function(){try{btn.disabled=true;const imageUrl=await uploadSelectedImage();const hidden=document.getElementById('listingImage');if(hidden)hidden.value=imageUrl;const original=window.__mfOriginalSaveListing;if(typeof original==='function')await original()}catch(e){const status=document.getElementById('listingStatusText');if(status)status.innerHTML='<span class="error">'+esc(e.message)+'</span>';btn.disabled=false}}}
function patchListing(){const original=window.saveListing;if(typeof original==='function'&&!window.__mfOriginalSaveListing)window.__mfOriginalSaveListing=original;setupImageUpload();bindListingUpload()}
function watchListing(){patchListing();const modal=document.getElementById('listingModal');if(modal)new MutationObserver(()=>patchListing()).observe(modal,{attributes:true,childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watchListing);else setTimeout(watchListing,0);
})();
