/* MINTFORGE Worldwide Shipping Engine v1 */
(() => {
  const SELLER_URL = 'https://zezusfnbqvijldhxoejd.supabase.co/functions/v1/seller-dashboard';
  const KEY = 'sb_publishable_ax8du05SKISdpJQkXb3Ulw_0YJKQTjzK';
  const COUNTRIES = window.MINTFORGE_COUNTRIES || [];
  const esc = v => String(v ?? '').replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const css = `.mf-shipbox{margin-top:16px;padding:16px;background:#0b0d11;border:1px solid #252932;border-radius:14px}.mf-shiphead{display:flex;justify-content:space-between;gap:10px;align-items:center}.mf-shipgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.mf-shipzones{display:grid;gap:9px;margin-top:12px}.mf-zone{padding:12px;border:1px solid #252932;border-radius:12px;background:#08090c}.mf-zone-top{display:flex;justify-content:space-between;gap:8px;align-items:center}.mf-zone-countries{font-size:11px;color:#9298a5;margin-top:7px;line-height:1.45}.mf-countrybox{max-height:190px;overflow:auto;border:1px solid #252932;border-radius:10px;padding:8px;background:#08090c;display:grid;grid-template-columns:repeat(2,1fr);gap:5px}.mf-countrybox label{font-size:11px;color:#c8cbd3;display:flex;gap:6px;align-items:center;padding:4px}.mf-countrybox input{accent-color:#9dff00}@media(max-width:700px){.mf-shipgrid,.mf-countrybox{grid-template-columns:1fr}}`;
  function addStyle(){if(document.getElementById('mfShipStyle'))return;const s=document.createElement('style');s.id='mfShipStyle';s.textContent=css;document.head.appendChild(s)}
  function api(action,body={}){const token=sessionStorage.getItem('mintforge_account_session');return fetch(SELLER_URL,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY,'Authorization':'Bearer '+KEY},body:JSON.stringify({action,session_token:token,...body})}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Shipping request failed');return d})}
  function countryOptions(selected=[]){const set=new Set(selected||[]);return COUNTRIES.map(c=>`<label><input type="checkbox" value="${c.code}" ${set.has(c.code)?'checked':''}>${esc(c.name)}</label>`).join('')}
  function zoneEditor(zone={},onSaved){
    const wrap=document.createElement('div');wrap.className='mf-zone';wrap.innerHTML=`<div class="mf-zone-top"><b>${zone.id?'Edit shipping zone':'New shipping zone'}</b><button type="button" class="mf-zone-remove">REMOVE</button></div><div class="mf-shipgrid"><div class="field"><label>ZONE NAME</label><input class="input mf-zname" value="${esc(zone.name||'Worldwide')}"></div><div class="field"><label>ZONE TYPE</label><select class="select mf-ztype"><option value="worldwide">Worldwide</option><option value="region">Country group</option><option value="country">Specific countries</option></select></div><div class="field"><label>SHIPPING</label><select class="select mf-zfree"><option value="free">Free shipping</option><option value="flat">Flat-rate</option></select></div><div class="field"><label>PRICE (AUD)</label><input class="input mf-zprice" type="number" min="0" step="0.01" value="${Number(zone.price_aud||0)}"></div><div class="field"><label>PROCESSING MIN DAYS</label><input class="input mf-zmin" type="number" min="0" step="1" value="${zone.processing_days_min??''}"></div><div class="field"><label>PROCESSING MAX DAYS</label><input class="input mf-zmax" type="number" min="0" step="1" value="${zone.processing_days_max??''}"></div></div><div class="field mf-country-wrap"><label>COUNTRIES INCLUDED</label><div class="mf-countrybox">${countryOptions(zone.countries||[])}</div></div><div class="field"><label>EXCLUDED COUNTRIES (ISO codes, comma separated)</label><input class="input mf-zexclude" value="${esc((zone.excluded_countries||[]).join(', '))}" placeholder="e.g. KP, IR"></div><div class="actions"><button type="button" class="primary mf-zone-save">${zone.id?'UPDATE ZONE':'SAVE ZONE'}</button><span class="status mf-zone-status"></span></div>`;
    const type=wrap.querySelector('.mf-ztype');type.value=zone.zone_type||'worldwide';const free=wrap.querySelector('.mf-zfree');free.value=zone.free_shipping?'free':'flat';const countries=wrap.querySelector('.mf-country-wrap');const sync=()=>{countries.style.display=type.value==='worldwide'?'none':'block'};type.addEventListener('change',sync);sync();
    wrap.querySelector('.mf-zone-remove').onclick=async()=>{if(zone.id){try{await api('delete_shipping_zone',{shipping_zone_id:zone.id})}catch(e){wrap.querySelector('.mf-zone-status').textContent=e.message;return}}wrap.remove();onSaved&&onSaved()};
    wrap.querySelector('.mf-zone-save').onclick=async()=>{const selected=[...wrap.querySelectorAll('.mf-countrybox input:checked')].map(x=>x.value);const z={name:wrap.querySelector('.mf-zname').value,zone_type:type.value,countries:selected,excluded_countries:wrap.querySelector('.mf-zexclude').value.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean),price_aud:Number(wrap.querySelector('.mf-zprice').value||0),free_shipping:free.value==='free',processing_days_min:wrap.querySelector('.mf-zmin').value===''?null:Number(wrap.querySelector('.mf-zmin').value),processing_days_max:wrap.querySelector('.mf-zmax').value===''?null:Number(wrap.querySelector('.mf-zmax').value),is_active:true};const st=wrap.querySelector('.mf-zone-status');st.textContent='Saving…';try{if(zone.id)await api('update_shipping_zone',{shipping_zone_id:zone.id,zone:z});else{const d=await api('create_shipping_zone',{zone:z});zone.id=d.shipping_zone.id}Object.assign(zone,z);st.textContent='Saved ✓';onSaved&&onSaved()}catch(e){st.textContent=e.message;st.classList.add('error')}};return wrap
  }
  function upgradeStateField(id){const old=document.getElementById(id);if(!old||old.dataset.mfState==='1')return;const input=document.createElement('input');input.className=old.className||'input';input.id=id;input.placeholder='State / Province / Region';input.autocomplete='address-level1';input.value=old.value||'';input.dataset.mfState='1';old.replaceWith(input)}
  function enhanceAccount(){
    addStyle();if(!document.getElementById('newListing'))return;const create=document.getElementById('storeCreate');if(!create||document.getElementById('mfShippingEngine'))return;const box=document.createElement('div');box.id='mfShippingEngine';box.className='mf-shipbox';box.innerHTML=`<div class="mf-shiphead"><div><h3 style="margin:0">Worldwide shipping</h3><p class="notice">Set shipping rules for this seller wallet. Specific countries override country groups, which override worldwide.</p></div><button type="button" id="mfAddZone" class="primary">+ ADD ZONE</button></div><div id="mfZones" class="mf-shipzones"></div>`;create.querySelector('.card').appendChild(box);const list=box.querySelector('#mfZones');box.querySelector('#mfAddZone').onclick=()=>list.appendChild(zoneEditor({name:'Worldwide',zone_type:'worldwide',free_shipping:true,price_aud:0},()=>{}));const original=window.sellerApi;if(typeof original==='function'){window.sellerApi=async function(action,body={}){const result=await original(action,body);if(action==='overview'&&result?.shipping_zones){list.innerHTML='';(result.shipping_zones||[]).forEach(z=>list.appendChild(zoneEditor(z,()=>{})));if(!result.shipping_zones.length)list.appendChild(zoneEditor({name:'Worldwide',zone_type:'worldwide',free_shipping:true,price_aud:0},()=>{}))}return result}}setTimeout(()=>{if(!list.children.length)list.appendChild(zoneEditor({name:'Worldwide',zone_type:'worldwide',free_shipping:true,price_aud:0},()=>{}))},500)
  }
  function enhanceCheckout(){
    addStyle();upgradeStateField('shipState');const select=document.getElementById('shipCountry');if(!select)return;const wrap=select.closest('.field');if(!document.getElementById('mfShipHint')){const hint=document.createElement('div');hint.className='shipnote';hint.id='mfShipHint';hint.textContent='Shipping is verified for your selected country at checkout.';wrap?.appendChild(hint)}const setCode=()=>{const opt=select.selectedOptions[0];if(opt&&opt.dataset.countryCode){select.dataset.countryCode=opt.dataset.countryCode;window.MINTFORGE_COUNTRY_CODE=opt.dataset.countryCode}};select.addEventListener('change',setCode);setCode();if(!window.__mfFetchWrapped){window.__mfFetchWrapped=true;const nativeFetch=window.fetch.bind(window);window.fetch=async function(input,init){const url=typeof input==='string'?input:(input?.url||'');if(url.includes('/create-checkout-v2')&&init?.body&&typeof init.body==='string'){try{const body=JSON.parse(init.body),s=body.shipping||{};if(!s.country_code){const found=COUNTRIES.find(c=>c.name===s.country);if(found){s.country_code=found.code;s.country_name=found.name;body.shipping=s;init={...init,body:JSON.stringify(body)}}}}catch{}}return nativeFetch(input,init)}}}
  function init(){setTimeout(enhanceAccount,250);setTimeout(enhanceCheckout,250);setTimeout(()=>upgradeStateField('profileState'),400);setTimeout(enhanceAccount,1200);setTimeout(enhanceCheckout,1200);setTimeout(()=>upgradeStateField('profileState'),1400)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
